server:
  port: 7000
spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: kopilochka
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/pet
  mvc:
    hiddenmethod:
      filter:
        enabled: true
